// Copyright (C) 2026 Barry Brown
// SPDX-License-Identifier: GPL-3.0-or-later

//! Bakes `data/words.db` into the binary at compile time.
//!
//! The SQLite file stays the canonical word store (rebuild it with
//! `tools/build_words.py`), but the game ships as a single self-contained
//! binary with no runtime database to locate or install.

use std::{env, fs, path::PathBuf};

fn main() {
    let root = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let db = root.join("data/words.db");
    println!("cargo:rerun-if-changed={}", db.display());
    println!("cargo:rerun-if-changed=build.rs");

    let conn = rusqlite::Connection::open_with_flags(
        &db,
        rusqlite::OpenFlags::SQLITE_OPEN_READ_ONLY,
    )
    .unwrap_or_else(|e| panic!("cannot open {}: {e}", db.display()));

    // One row per playable word; glosses from every sense are joined so the
    // reveal can show both the classical and the New Testament meaning.
    let mut stmt = conn
        .prepare(
            "SELECT w.word, w.display, w.is_answer,
                    (SELECT group_concat(g, ' · ') FROM (
                        SELECT DISTINCT s.gloss AS g FROM sense s
                        WHERE s.word_id = w.id ORDER BY s.frequency DESC))
             FROM word w ORDER BY w.word",
        )
        .unwrap();

    let rows: Vec<(String, String, bool, String)> = stmt
        .query_map([], |r| {
            Ok((
                r.get(0)?,
                r.get(1)?,
                r.get::<_, i64>(2)? != 0,
                r.get::<_, Option<String>>(3)?.unwrap_or_default(),
            ))
        })
        .unwrap()
        .map(Result::unwrap)
        .collect();

    assert!(!rows.is_empty(), "word database is empty");
    assert!(
        rows.iter().any(|r| r.2),
        "word database has no answer-eligible words"
    );

    let mut out = String::from(
        "// @generated by build.rs from data/words.db - do not edit.\n\
         // Included into src/words.rs, which defines Entry.\n\n\
         pub static WORDS: &[Entry] = &[\n",
    );
    for (word, display, is_answer, gloss) in &rows {
        assert_eq!(
            word.chars().count(),
            5,
            "word {word:?} is not five characters"
        );
        out.push_str(&format!(
            "    Entry {{ word: {word:?}, display: {display:?}, gloss: {gloss:?}, is_answer: {is_answer} }},\n"
        ));
    }
    out.push_str("];\n");

    let dest = PathBuf::from(env::var("OUT_DIR").unwrap()).join("words_generated.rs");
    fs::write(&dest, out).unwrap();
    println!(
        "cargo:warning=embedded {} words ({} answers)",
        rows.len(),
        rows.iter().filter(|r| r.2).count()
    );
}
